# Auto label all PRs so that they can be autosquashed
name: Auto label Pull Requests
on:
  - pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
