---
name: Merge ready PRs
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'abatilo' || github.actor == 'abatilo-bot[bot]' || github.actor == 'dependabot[bot]'
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
          MERGE_METHOD: "squash"
          MERGE_RETRY_SLEEP: "30000"
