name: Upload test coverage
on: push

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1.0.1

      # Check go vendor cache
      - name: Cache go dependencies
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Vendor dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: |
          go mod vendor

      - name: Generate coverage report
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg ./... ./...
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
