---
name: Label PRs
"on":
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ steps.generate_token.outputs.token }}"
