---
name: Semantic PR
"on": pull_request

jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
